# Generated by Django 3.1 on 2022-03-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_manager_department'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='department',
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.ManyToManyField(blank=True, null=True, to='departments.Department'),
        ),
    ]
