# Generated by Django 3.1 on 2022-03-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_manager_department'),
        ('profiles', '0002_auto_20220313_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ManyToManyField(blank=True, to='departments.Department'),
        ),
    ]
