# Generated by Django 3.1 on 2022-01-31 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0018_auto_20220131_2208'),
        ('profiles', '0009_auto_20220131_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='departments.department'),
        ),
    ]
