# Generated by Django 3.2 on 2022-03-24 03:24

from django.db import migrations, models
import utils.model_utils


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.CharField(default=utils.model_utils.generate_id, editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
