# Generated by Django 3.2 on 2022-03-24 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('news', '0003_news_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.gallery', verbose_name='Галерея'),
        ),
    ]
