# Generated by Django 3.2 on 2022-04-10 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='is_active',
        ),
    ]
