# Generated by Django 3.1 on 2022-02-03 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0022_auto_20220203_2050'),
        ('speciality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.department'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='name',
            field=models.CharField(max_length=150, verbose_name='имя специальность'),
        ),
    ]
