# Generated by Django 3.2 on 2022-04-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speciality', '0003_remove_speciality_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
    ]
