# Generated by Django 4.0.2 on 2022-02-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='para',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='none', max_length=10, verbose_name='Пара'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='type',
            field=models.CharField(choices=[('lecture', 'Лекция'), ('practice', 'Практика'), ('laboratory_work', 'Лабораторная работа'), ('course_work', 'Курсовая работа'), ('diplom_work', 'Дипломная работа'), ('assessment', 'Зачет'), ('assessment_with_score', 'Зачет с оценкой'), ('exam', 'Экзамен')], default='none', max_length=30, verbose_name='Тип занятий'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='visit',
            field=models.CharField(choices=[('remote', 'Удаленная'), ('locale', 'Очная')], default='none', max_length=10, verbose_name='Тип пары'),
        ),
    ]
