# Generated by Django 3.2 on 2022-04-13 17:03

from django.db import migrations, models
import utils.model_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.CharField(default=utils.model_utils.generate_id, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=150, verbose_name='Код группы')),
                ('email', models.CharField(max_length=50, verbose_name='Почта группы')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер телефона')),
                ('visit_type', models.CharField(choices=[('remote', 'Удаленная'), ('locale', 'Очная')], default='locale', max_length=10, verbose_name='Тип группы')),
                ('start_date', models.DateField(verbose_name='Начало обучения')),
                ('is_session', models.BooleanField(default=False, verbose_name='Началась ли сессия?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
    ]
