# Generated by Django 3.1 on 2022-02-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.CharField(default='50588d9d2e', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=150, verbose_name='Код группы')),
                ('email', models.CharField(max_length=50, verbose_name='Почта группы')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('start_date', models.DateField(verbose_name='Начало обучения')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
    ]
