# Generated by Django 3.1 on 2022-02-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20220203_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.CharField(default='e15e5c1391', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
