# Generated by Django 3.1 on 2022-03-09 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_auto_20220203_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curator', to=settings.AUTH_USER_MODEL, verbose_name='Куратор'),
        ),
        migrations.AddField(
            model_name='group',
            name='is_session',
            field=models.BooleanField(default=False, verbose_name='Началась ли сессия?'),
        ),
        migrations.AddField(
            model_name='group',
            name='visit_type',
            field=models.CharField(choices=[('remote', 'Удаленная'), ('locale', 'Очная')], default='none', max_length=10, verbose_name='Тип группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.CharField(default='363ddfabd6', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
