# Generated by Django 3.1 on 2022-02-12 12:58

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20220212_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=10, max_length=10, prefix='', primary_key=True, serialize=False, unique=True),
        ),
    ]
