# Generated by Django 3.1 on 2022-01-31 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(default='e5a16806c1', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150, verbose_name='Название кафедры')),
                ('email', models.CharField(max_length=50, verbose_name='Почта')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, upload_to='department/', verbose_name='Фотография')),
                ('photos', models.ImageField(blank=True, upload_to='department/', verbose_name='Фотографии')),
                ('manager_department', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_department', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедры',
            },
        ),
    ]
