# Generated by Django 3.1 on 2022-03-13 10:58

from django.db import migrations, models
import utils.model_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(default=utils.model_utils.generate_id, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150, verbose_name='Название кафедры')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Почта')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер телефона')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('basic_timetable_department', models.FileField(blank=True, null=True, upload_to='timetable-d/', verbose_name='Основное рассписание')),
                ('session_timetable_department', models.FileField(blank=True, null=True, upload_to='timetable-d/', verbose_name='Рассписание сессии')),
                ('session_absentia_timetable_department', models.FileField(blank=True, null=True, upload_to='timetable-d/', verbose_name='Рассписание сессии заочно')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='department/', verbose_name='Фотография')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='department/', verbose_name='Фотографии')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедры',
            },
        ),
    ]
