# Generated by Django 3.1 on 2022-02-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(default='1bde9db45e', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150, verbose_name='Название кафедры')),
                ('email', models.CharField(max_length=50, verbose_name='Почта')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='department/', verbose_name='Фотография')),
                ('photos', models.ImageField(blank=True, upload_to='department/', verbose_name='Фотографии')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедры',
            },
        ),
    ]
