# Generated by Django 3.1 on 2022-01-31 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='82d37d6f5e', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
