# Generated by Django 3.1 on 2022-02-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_manager_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='c06ac20c5e', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
