# Generated by Django 3.1 on 2022-03-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_manager_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='basic_timetable_department',
            field=models.FileField(upload_to='timetable-d/', verbose_name='Основное рассписание'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название кафедры'),
        ),
        migrations.AlterField(
            model_name='department',
            name='photos',
            field=models.ImageField(upload_to='department/', verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='department',
            name='session_absentia_timetable_department',
            field=models.FileField(upload_to='timetable-d/', verbose_name='Рассписание сессии заочно'),
        ),
        migrations.AlterField(
            model_name='department',
            name='session_timetable_department',
            field=models.FileField(upload_to='timetable-d/', verbose_name='Рассписание сессии'),
        ),
    ]
