# Generated by Django 3.1 on 2022-01-31 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_auto_20220131_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='ff90ec833e', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
