# Generated by Django 3.1 on 2022-03-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_manager_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='basic_timetable_department',
            field=models.FileField(blank=True, null=True, upload_to='timetable-d/', verbose_name='Основное рассписание'),
        ),
        migrations.AddField(
            model_name='department',
            name='session_absentia_timetable_department',
            field=models.FileField(blank=True, null=True, upload_to='timetable-d/', verbose_name='Рассписание сессии заочно'),
        ),
        migrations.AddField(
            model_name='department',
            name='session_timetable_department',
            field=models.FileField(blank=True, null=True, upload_to='timetable-d/', verbose_name='Рассписание сессии'),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='b3b974d3c0', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
