# Generated by Django 3.1 on 2022-02-12 12:58

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_auto_20220212_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='timetable_department',
            field=models.FileField(blank=True, null=True, upload_to='timetable-d/', verbose_name='Рассписание'),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=10, max_length=10, prefix='', primary_key=True, serialize=False, unique=True),
        ),
    ]
