# Generated by Django 3.1 on 2022-03-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_auto_20220310_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='department',
            name='basic_timetable_department',
            field=models.FileField(blank=True, null=True, upload_to='timetable-d/', verbose_name='Основное рассписание'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='department',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название кафедры'),
        ),
        migrations.AlterField(
            model_name='department',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='department',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='department/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='department',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='department/', verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='department',
            name='session_absentia_timetable_department',
            field=models.FileField(blank=True, null=True, upload_to='timetable-d/', verbose_name='Рассписание сессии заочно'),
        ),
        migrations.AlterField(
            model_name='department',
            name='session_timetable_department',
            field=models.FileField(blank=True, null=True, upload_to='timetable-d/', verbose_name='Рассписание сессии'),
        ),
    ]
