# Generated by Django 3.1 on 2022-01-31 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_auto_20220131_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='49363c98e0', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
