# Generated by Django 3.2 on 2022-03-21 02:23

import departments.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_auto_20220317_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='original_basic_timetable_department',
            field=models.FileField(blank=True, null=True, upload_to='timetable-original/', validators=[departments.validators.validate_file_extension], verbose_name='Оригинал основного рассписания'),
        ),
        migrations.AddField(
            model_name='department',
            name='original_session_absentia_timetable_department',
            field=models.FileField(blank=True, null=True, upload_to='timetable-original/', validators=[departments.validators.validate_file_extension], verbose_name='Оригинальное расписание сессии заочно'),
        ),
        migrations.AddField(
            model_name='department',
            name='original_session_timetable_department',
            field=models.FileField(blank=True, null=True, upload_to='timetable-original/', validators=[departments.validators.validate_file_extension], verbose_name='Оригинальное расписание сессии'),
        ),
    ]
