# Generated by Django 3.1 on 2022-03-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_auto_20220309_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='5849a5bef2', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
