# Generated by Django 3.1 on 2022-01-31 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_auto_20220131_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='5e25dcaa2c', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
