# Generated by Django 3.2 on 2022-03-24 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('departments', '0004_auto_20220321_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='photos',
        ),
        migrations.AddField(
            model_name='department',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.gallery'),
        ),
    ]
