# Generated by Django 3.2 on 2022-03-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_auto_20220324_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='gallery',
        ),
        migrations.AddField(
            model_name='department',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='department/', verbose_name='Фотографии'),
        ),
    ]
