# Generated by Django 3.1 on 2022-01-31 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_auto_20220131_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='a2988674b1', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
