# Generated by Django 3.2 on 2022-03-24 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('departments', '0006_auto_20220324_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.gallery'),
        ),
    ]
