# Generated by Django 3.1 on 2022-01-31 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0014_auto_20220131_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='08a773b07a', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
