# Generated by Django 3.1 on 2022-01-31 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0018_auto_20220131_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='a55474f39a', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
