# Generated by Django 3.1 on 2022-02-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0020_auto_20220131_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='376748aea4', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
