# Generated by Django 3.1 on 2022-02-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0021_auto_20220203_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='3a52db508e', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
