# Generated by Django 3.1 on 2022-02-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0022_auto_20220203_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='ed7e6afd5b', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
