# Generated by Django 3.1 on 2022-01-31 19:49

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=10, max_length=10, prefix='', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150, verbose_name='Название кафедры')),
                ('email', models.CharField(max_length=50, verbose_name='Почта')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('number_of_groups', models.PositiveIntegerField(default=0, verbose_name='Количество групп')),
                ('number_of_specialties', models.PositiveIntegerField(default=0, verbose_name='Количество специальностей')),
                ('count_of_students', models.CharField(max_length=50, verbose_name='Количество студентов')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='department/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедры',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=10, max_length=10, prefix='', primary_key=True, serialize=False, unique=True)),
                ('group_number', models.CharField(max_length=150, verbose_name='Номер группы')),
                ('count_of_students', models.CharField(blank=True, max_length=50, verbose_name='Количество студентов')),
                ('name_of_specialty', models.CharField(max_length=100, verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
    ]
