# Generated by Django 3.2.8 on 2021-12-09 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.CharField(default='myu5uVUDT5kYTv5T6z3RQT', editable=False, max_length=22, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('birthday', models.DateField(default=datetime.date.today, verbose_name='Дата рождения')),
                ('group_number', models.CharField(max_length=20, verbose_name='Номер группы')),
                ('course_number', models.CharField(max_length=10, verbose_name='Номер курса')),
                ('headman', models.BooleanField(default=False, verbose_name='Староста')),
                ('email', models.CharField(max_length=50, verbose_name='Почта')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('phone_number_parents', models.CharField(max_length=50, verbose_name='Контактный телефон родителей')),
                ('photo', models.TextField(blank=True, verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.CharField(default='WP6qakmswpaMqsnnDJjE84', editable=False, max_length=22, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('birthday', models.CharField(max_length=50, verbose_name='Дата рождения')),
                ('email', models.CharField(max_length=50, verbose_name='Почта')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('photo', models.ImageField(upload_to='teachers/', verbose_name='Фотография')),
                ('position', models.CharField(max_length=50, verbose_name='Должность')),
                ('qualification', models.CharField(max_length=50, verbose_name='Квалификация')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
    ]
