# Generated by Django 3.1 on 2022-01-04 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='id',
            field=models.CharField(default='HTGYUyTjZWWcj3fJCbVzKb', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='students',
            name='photo',
            field=models.ImageField(upload_to='students/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='id',
            field=models.CharField(default='23Md9MvUpBhtYrRf6Nm8Mc', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.CharField(default='SimkVkEJdU3KFkVKu5SCQs', editable=False, max_length=22, primary_key=True, serialize=False)),
                ('group_number', models.CharField(max_length=150, verbose_name='Номер группы')),
                ('number_of_students', models.CharField(max_length=50, verbose_name='Количество студентов')),
                ('name_of_specialty', models.CharField(max_length=100, verbose_name='Специальность')),
                ('headman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.students', verbose_name='Староста')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(default='ASyrwibewZFzKMizMRe5BJ', editable=False, max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Название кафедры')),
                ('email', models.CharField(max_length=50, verbose_name='Почта')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('number_of_groups', models.PositiveIntegerField(default=0, verbose_name='Количество групп')),
                ('number_of_specialties', models.PositiveIntegerField(default=0, verbose_name='Количество групп')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='department/', verbose_name='Фотография')),
                ('manager_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.teachers', verbose_name='Заведующий кафедры')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедры',
            },
        ),
        migrations.AddField(
            model_name='students',
            name='cathedra_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.department', verbose_name='Кафедра'),
        ),
    ]
