# Generated by Django 3.1 on 2022-01-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20220104_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='3AZbBfAJoP27nkLpYjrnpX', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='groups',
            name='id',
            field=models.CharField(default='JwgjvkjhyNPQgTreaFVjnd', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='students',
            name='id',
            field=models.CharField(default='3Db9feA45mMBDTqxMQTyNq', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='id',
            field=models.CharField(default='UHShjR3buK78JeGvjbV2xm', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
