# Generated by Django 3.1 on 2022-01-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_auto_20220106_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='Ga8zmxyrzH4sXEE39rDHpe', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='groups',
            name='id',
            field=models.CharField(default='6HvKvShzSyj46hHdTopN9M', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='students',
            name='id',
            field=models.CharField(default='JJneLwCfmzGscSxSvy9SuY', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='id',
            field=models.CharField(default='YvU9uRkTTDnnFXmk6JLWdP', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
