# Generated by Django 3.1 on 2022-01-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_auto_20220106_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='jYawwZuoRwzLZrTHTDMoAE', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='groups',
            name='id',
            field=models.CharField(default='VrdH3sv8NsGqdXfAMjKdh3', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='students',
            name='id',
            field=models.CharField(default='5hRMwg95ZvE5y5cSappPC3', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='id',
            field=models.CharField(default='h6BffjjcWS25ykg5DfPyzP', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
