# Generated by Django 3.1 on 2022-01-06 12:31

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_auto_20220106_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=10, max_length=10, prefix='N', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='groups',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=10, max_length=10, prefix='N', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='students',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=10, max_length=10, prefix='N', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=10, max_length=10, prefix='N', primary_key=True, serialize=False),
        ),
    ]
